[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.25"
remappings = [
  "@openzeppelin/contracts@5.0.2/=lib/icm-contracts/lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/",
  "@teleporter/=lib/icm-contracts/contracts/teleporter/",
  "@utilities/=lib/icm-contracts/contracts/utilities/"
]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
